
import auth from '../components/Templates/images/auth.svg'
import header from '../components/Templates/images/header.svg'
import blog from '../components/Templates/images/blog.svg'
import card from '../components/Templates/images/card.svg'

export const CompIndustry=[
    {
        id:1,
        name:"Authentication",
        image:card,
        link:"auth",
    },
    {
        id:2,
        name:"Alerts",
        image:header,
        link:"alert",
    },
    {
        id:3,
        name:"Address",
        image:blog,
        link:"address",
    },
    {
        id:4,
        name:"Admin",
        image:auth,
        about:"All Components are customizable. Customize According to your Design.",
        link:"#",
    },
    {
        id:5,
        name:"Blog",
        image:auth,
        about:"All Components are customizable. Customize According to your Design.",
        link:"blog",
    },
    {
        id:6,
        name:"Buttons",
        image:auth,
        about:"All Components are customizable. Customize According to your Design.",
        link:"button",
    },
    {
        id:7,
        name:"Breadcrumbs",
        image:auth,
        about:"All Components are customizable. Customize According to your Design.",
        link:"#",
    },
    {
        id:8,
        name:"Banners",
        image:auth,
        about:"All Components are customizable. Customize According to your Design.",
        link:"#",
    },
    {
        id:8,
        name:"Call to Action",
        image:auth,
        about:"All Components are customizable. Customize According to your Design.",
        link:"#",
    },
    {
        id:8,
        name:"Content",
        image:auth,
        about:"All Components are customizable. Customize According to your Design.",
        link:"#",
    },
    {
        id:8,
        name:"Contact",
        image:auth,
        about:"All Components are customizable. Customize According to your Design.",
        link:"contact",
    },
    {
        id:8,
        name:"Carousel",
        image:auth,
        about:"All Components are customizable. Customize According to your Design.",
        link:"#",
    },
    {
        id:8,
        name:"Feature",
        image:auth,
        about:"All Components are customizable. Customize According to your Design.",
        link:"#",
    },
    {
        id:8,
        name:"FAQ",
        image:auth,
        about:"All Components are customizable. Customize According to your Design.",
        link:"faqcomp",
    },
    {
        id:8,
        name:"Forms",
        image:auth,
        about:"All Components are customizable. Customize According to your Design.",
        link:"#",
    },
    {
        id:8,
        name:"Footers",
        image:auth,
        about:"All Components are customizable. Customize According to your Design.",
        link:"footers",
    },
    {
        id:8,
        name:"Navbar",
        image:auth,
        about:"All Components are customizable. Customize According to your Design.",
        link:"#",
    },
    {
        id:8,
        name:"Gallery",
        image:auth,
        about:"All Components are customizable. Customize According to your Design.",
        link:"#",
    },
    {
        id:8,
        name:"Hero",
        image:auth,
        about:"All Components are customizable. Customize According to your Design.",
        link:"hero",
    },
    {
        id:8,
        name:"Pricing",
        image:auth,
        about:"All Components are customizable. Customize According to your Design.",
        link:"#",
    },
    {
        id:8,
        name:"Pagination",
        image:'https://ik.imagekit.io/vpa3fwqdnd/Components/contact_n8VSUzNXy.svg',
        about:"All Components are customizable. Customize According to your Design.",
        link:"#",
    },
]